# Generated by Django 3.1.6 on 2021-04-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='counter',
            field=models.PositiveIntegerField(default=0, help_text='counts number of category'),
            preserve_default=False,
        ),
    ]
